### PR TITLE
[Play] - Error handling on SelectAvatar click of Pregame Flow

### PR DESCRIPTION
**Pull request by Alexandra-Kushnirsky**
**Issue:**
This PR addresses git issue #671: 
No UI error handling for API errors on choose avatar screen

**Resolution:**
As was suggested, the solution was to incorporate the ErrorModal component into the SelectAvatar component by passing in relevant information from PregameContainer to SelectAvatar and expand ErrorModal's functionality to respond to errors when players fail to join the game.

Relevant code:
_Adding ErrorModal for Pregame_:
In `PregameContainer.tsx`:
-Pass `APIError` into `<SelectAvatar>` on `line 164` to determine if error modal should be displayed
In `SelectAvatar.tsx`:
-`<ErrorModal>` component added on `lines 116-121`, taking in `displayErrorModal` (passed in from parent as `APIError`) as an argument for `isModalOpen` on `line 117`
In `PlayModels.tsx`:
-Added element to `ErrorType` enum called `JOIN` on `line 108` to enable unique error message for that case
In `ErrorModal.tsx`:
-Use the above enum element `JOIN` in `const upperTextMap` on `line 35`: `[ErrorType.JOIN]: t('error.connect.join')`
In `translation.json` (both en and es):
-Add `"join": "Unable to join game. Please try again"`(and (google) translated Spanish version to es file) to `error.connect` item in json on `line 112` 

_Button handling:_
In `PregameContainer.tsx`:
-Added boolean `const [reenableChooseButton, setReenableChooseButton]` on `line 44` to be updated in `handleRetryJoin` on `line 59` and eventually passed down to `<SelectAvatar>` on `line 166`
In `SelectAvatar.tsx`:
-This value is passed into `reenableButton` and is used to check if the button should be disabled: 
`disabled={isButtonPressed && !reenableButton}` (`line 162`) since we want the player to be able to press the button again after closing the errorModal (if it appears)

_Handling 'try again' press event on modal_:
In `PregameContainer.tsx`:
-Added function `handleRetryJoin()` on `lines 57-60` which sets `APIError` to false and re-enables the button described above. This function then gets passed down to `<SelectAvatar>` on `line 165`
In `SelectAvatar.tsx`:
-`handleRetry` function is passed into `<ErrorModal>` component on `line 120`

**Preview:**
I simulated APIError with some dummy code for testing purposes below:
Screenshot of error modal on select avatar screen:
Screenshot 2023-06-20 at 8 18 31 PM

Screen recording of player attempting to join game when APIError has occurred:

https://github.com/rightoneducation/righton-app/assets/106450593/cb7220aa-e301-46ab-9013-ab265cd4be8b

@drewjhart , @maniramezan

### CODE REVIEW

**Review by drewjhart — CHANGES_REQUESTED** [review]
Great job on this. A+ on integrating the new error mode into the existing `ErrorModal.tsx` and providing an additional label in the `ErrorType.`

A couple things:
1. Could we rename APIError to isAPIError? This is my bad. 
2. Instead of having a separate `reenabledButton` I think we can probably just use `isAPIError` as both the means through which to disable the button and to show the modal. 

```
In pseudo code:

In PregameContainer, pass isAPIError to selectAvatar directly:
<SelectAvatar isAPIError={isAPIError}  />

In SelectAvatar.tsx, pass isAPIError to ErrorModal and control button with isAPIError and isButtonPressed:

<ErrorModal isModalOpen={isAPIError} />

<GamePlayButtonStyled 
    disabled={isButtonPressed || isAPIError} />
    
    
Then the only thing that changes on handleRetryClick is setAPIError = false;
```


Pretty much what you had but we can remove the `setReeenableChooseButton` then.

**Comment by Alexandra-Kushnirsky** [comment]
> Great job on this. A+ on integrating the new error mode into the existing `ErrorModal.tsx` and providing an additional label in the `ErrorType.`
> 
> A couple things:
> 
> 1. Could we rename APIError to isAPIError? This is my bad.
> 2. Instead of having a separate `reenabledButton` I think we can probably just use `isAPIError` as both the means through which to disable the button and to show the modal.
> 
> ```
> In pseudo code:
> 
> In PregameContainer, pass isAPIError to selectAvatar directly:
> <SelectAvatar isAPIError={isAPIError}  />
> 
> In SelectAvatar.tsx, pass isAPIError to ErrorModal and control button with isAPIError and isButtonPressed:
> 
> <ErrorModal isModalOpen={isAPIError} />
> 
> <GamePlayButtonStyled disabled={isButtonPressed || isAPIError} />
>     
> Then the only thing that changes on handleRetryClick is setAPIError = false;
> ```
> 
> Pretty much what you had but we can remove the `setReeenableChooseButton` then.

hmm so I initially did try to just use isAPIError to set disabled in the choose button but I ran into the following:
in the case where disabled is set by isButtonPressed || isAPIError,
The choose button is still disabled after the player presses "try again" on the modal. As an example to see why this is the case:
Let’s say there is an API error, the flow would look something like this:
(1) Since there is an API error, isAPIError is true
(2) player presses ‘choose’ button for the first time
(3) ErrorModal pops up
(4) User presses ‘try again’ button on modal which triggers handleRetryJoin function
(5) handleRetryJoin sets isAPIError to false and error modal closes
(6) However, now disabled evaluates to: disabled = {isButtonPressed = true || isAPIError = false} = true
That was the reason for reenableChooseButton but I'm sure there's a better way of handling that logic. I can keep looking for a better solution

**Comment by drewjhart** [comment]
> > Great job on this. A+ on integrating the new error mode into the existing `ErrorModal.tsx` and providing an additional label in the `ErrorType.`
> > A couple things:
> > 
> > 1. Could we rename APIError to isAPIError? This is my bad.
> > 2. Instead of having a separate `reenabledButton` I think we can probably just use `isAPIError` as both the means through which to disable the button and to show the modal.
> > 
> > ```
> > In pseudo code:
> > 
> > In PregameContainer, pass isAPIError to selectAvatar directly:
> > <SelectAvatar isAPIError={isAPIError}  />
> > 
> > In SelectAvatar.tsx, pass isAPIError to ErrorModal and control button with isAPIError and isButtonPressed:
> > 
> > <ErrorModal isModalOpen={isAPIError} />
> > 
> > <GamePlayButtonStyled disabled={isButtonPressed || isAPIError} />
> >     
> > Then the only thing that changes on handleRetryClick is setAPIError = false;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Pretty much what you had but we can remove the `setReeenableChooseButton` then.
> 
> hmm so I initially did try to just use isAPIError to set disabled in the choose button but I ran into the following: in the case where disabled is set by isButtonPressed || isAPIError, The choose button is still disabled after the player presses "try again" on the modal. As an example to see why this is the case: Let’s say there is an API error, the flow would look something like this: (1) Since there is an API error, isAPIError is true (2) player presses ‘choose’ button for the first time (3) ErrorModal pops up (4) User presses ‘try again’ button on modal which triggers handleRetryJoin function (5) handleRetryJoin sets isAPIError to false and error modal closes (6) However, now disabled evaluates to: disabled = {isButtonPressed = true || isAPIError = false} = true That was the reason for reenableChooseButton but I'm sure there's a better way of handling that logic. I can keep looking for a better solution

Oh good point, I hadn't thought about that. We could try having two callbacks from the ErrorModal, instead of one that runs all the way back to PregameContainer.tsx:

```
PregameContainer:

const [isAPIError, setIsAPIError] = useState(false);
<selectAvatar ... isAPIError={isAPIError} setIsAPIError={setIsAPIError} />

SelectAvatar:

const [isButtonPressed, SetIsButtonPressed] = useState(false);
handleErrorModalClick = () => { // callback from error modal
     setIsButtonPressed(false); // reset button
    setIsAPIError(false); //call back directly to set state 
}

<ErrorModal isModalOpen={isAPIError} handleErrorModalClick={handleErrorModalClick}/>
<Button disabled={isButtonPressed || isAPIError} /> // not even sure if the isAPIError is need tbh 
```

I don't know. Seems kind of weird to have a callback within a callback like this but I feel it reads clearer than the double variables for the buttons. We can also probably just remove the || isAPIError because the modal will always block the selectAvatar button.

What do you think though? Do you know a better way than just nesting the callbacks?

**Comment by Alexandra-Kushnirsky** [comment]
Honestly, I think the callbacks do read much clearer than having an additional (unnecessary) variable being passed between components for the button and I can't really think of a better solution at the moment without introducing more constants (which again are probably unnecessary). If it's all good with you I think I'll go ahead and implement the callback solution

**Comment by drewjhart** [comment]
> Honestly, I think the callbacks do read much clearer than having an additional (unnecessary) variable being passed between components for the button and I can't really think of a better solution at the moment without introducing more constants (which again are probably unnecessary). If it's all good with you I think I'll go ahead and implement the callback solution

Sweet sounds good, appreciate the opinion. I'll watch for the push and then approve the PR when you're good to go.

**Review by drewjhart — APPROVED** [review]

**Pull request merged**
