### PR TITLE
[Host] - Scroll screen on graph click

### PR DESCRIPTION
**Pull request by Alexandra-Kushnirsky**
**Issue:**
Currently, we are scrolling to the top of the screen when a component is clicked: https://github.com/rightoneducation/righton-app/issues/906 

**Resolution:**
Changed ref to point to subcomponent containing text that says "Showing players who answered:"

Relevant code:
- In `host` > `src` > `components` > `GameInProgressContentSwitch.jsx` > lines `57-82`: removed ref assignment from parent div and added new div wrapper with ref assignment to component we want to scroll to on `lines 70, 71`: 
`<div id="responses-scrollbox"
              ref={responsesRef}>
              <SelectedAnswer...`

**Preview:**
In the below video, we can see the scroll behavior on bar click has changed so that we focus on the subcomponent containing text that says "Showing players who answered:"

https://github.com/rightoneducation/righton-app/assets/106450593/7f41fb3a-89a6-4241-94dd-2f00b4516ec0

@drewjhart

### CODE REVIEW

**Comment by drewjhart** [comment]
Looks like it's working as it should, nice. Would you be able to do a video where there are like 10 players (it will be super annoying to generate)? I just want to test the scroll when that list of players doesn't fit on the screen

**Comment by Alexandra-Kushnirsky** [comment]
https://github.com/rightoneducation/righton-app/assets/106450593/94ae50ab-3980-4046-897b-1e575faeb789

**Comment by drewjhart** [comment]
Thanks for updating this video, Alex - even if it was a pain. Is there a way to get the 'Players Who Have Answered' component to the top of the screen when a user clicks the bar graph? I think right now it's just ensuring that the component is entirely on the screen but it would be good to get it at a consistent place.

**Comment by Alexandra-Kushnirsky** [comment]
No problem at all! I changed `responsesRef.current.scrollIntoView({ behavior: 'smooth'});` to `responsesRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });` on `line 154` of `host`>`src`>`pages`>`GameInProgress.jsx` so that the component we're targeting scrolls to the highest permittable vertical position on the screen. Basically, this means if there are only a few players that selected that answer, it won't go all the way to the top since there would be blank space underneath but if we want this to be the case, I can find a different solution. Here is a video with the new behavior below. You can see both cases where (1) there are many players who selected an answer and thus the dropdown takes up a significant portion of the screen and (2) the opposite case where only a few players selected an answer:


https://github.com/rightoneducation/righton-app/assets/106450593/d61cfec1-dfa0-446e-a50f-2ba2cb1f0841

**Comment by drewjhart** [comment]
> No problem at all! I changed `responsesRef.current.scrollIntoView({ behavior: 'smooth'});` to `responsesRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });` on `line 154` of `host`>`src`>`pages`>`GameInProgress.jsx` so that the component we're targeting scrolls to the highest permittable vertical position on the screen. Basically, this means if there are only a few players that selected that answer, it won't go all the way to the top since there would be blank space underneath but if we want this to be the case, I can find a different solution. Here is a video with the new behavior below. You can see both cases where (1) there are many players who selected an answer and thus the dropdown takes up a significant portion of the screen and (2) the opposite case where only a few players selected an answer:
> 
>  Screen.Recording.2023-12-20.at.4.01.36.PM.mov

Sick, looks good, nice one. @amarax and @sincwu, is this the kind of behaviour you're looking for in the scroll on the click of a bar?

**Comment by drewjhart** [comment]
@amarax mentioned that he's reviewing some broader UI things before commenting on these issues but that we shouldn't let him hold us up. I'm going to merge this and then he can follow up with comments next week. @Alexandra-Kushnirsky @sincwu

**Pull request merged**
