### PR TITLE
[Play] - New Score Animation

### PR DESCRIPTION
**Pull request by drewjhart**
**Issue:**
It was determined that the new score animation (when a player is awarded points) isn't noticable enough on the screen. 

**Resolution:**
The animation was adjusted to add a rotation and to increase the duration. 

Relevant code:
- `ScoreIndicator.tsx`:
```
 '@keyframes newScoreUp': {
    '0%': { transform: 'translateY(-110%) rotate(0deg) scale(1.0)' },
    '10%': { opacity: 1, transform: 'translateY(-110%) rotate(0deg) scale(1.2)' },
    '15%, 25%': { opacity: 1, transform: 'translateY(-110%) rotate(-12deg) scale(1.2)' },
    '20%, 30%': { opacity: 1, transform: 'translateY(-110%) rotate(12deg) scale(1.2)' },
    '40%': { opacity: 1, transform: 'translateY(-110%) rotate(0deg) scale(1.0)' },
    '100%': { transform: 'translateY(0)' },
  },
```

Updated 08/10/2023 per feedback with:

```
const NewPointsAnimation = styled('div')({
  opacity: 0,
  position: 'absolute',
  zIndex: 2,
  animation: `
   newScoreUpWiggle 1500ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,
   newScoreUpBounce 300ms ease-in-out 1500ms, 
   newScoreUpFadeDown 1000ms ease-in-out 1800ms
  `,
  '@keyframes newScoreUpWiggle': {
      '0%': { 
        transform: 'translateY(-110%) rotate(0deg) scale(1.0)' 
      },
      '10%': { 
        opacity: 1, 
        transform: 'translateY(-110%) rotate(0deg) scale(1.2)' 
      },
      '15%, 45%, 75%': { 
        opacity: 1, 
        transform: 'translateY(-110%) rotate(-12deg) scale(1.2)' 
      },
      '30%, 60%': { 
        opacity: 1, 
        transform: 'translateY(-110%) rotate(12deg) scale(1.2)' 
      },
      '90%': { 
        opacity: 1, 
        transform: 'translateY(-110%) rotate(0deg) scale(1.2)' 
      },
      '100%': { 
        opacity: 1, 
        transform: 'translateY(-110%) rotate(0deg) scale(1.0)' 
      },
    },
    '@keyframes newScoreUpBounce': {
      '0%, 100%': {
        opacity: 1, 
        transform: 'translateY(-110%)' 
      },
      '50%': {
        opacity: 1, 
        transform: 'translateY(-130%)' 
      },
    },
    '@keyframes newScoreUpFadeDown': {
      '0%': {
        opacity: 1, 
        transform: 'translateY(-110%)' 
      },
      '100%': { 
        transform: 'translateY(0%)' 
      },
    },
});
```
and
```
const ScoreAnimation = styled('div', {
  shouldForwardProp: (prop) => prop !== 'startAnimation',
})<ScoreAnimationProps>(({ startAnimation }) => ({
  opacity: 1,
  zIndex: 2,
  animation: startAnimation ? `
   scoreGrow 1000ms ease-in-out 0ms
  `: ``,
  '@keyframes scoreGrow': {
      '0%, 100%': { 
        opacity: 1,
        transform: ' scale(1.0)' 
      },
      '50%': { 
        opacity: 1,
        transform: ' scale(1.2)' 
      },
    },
}));
```

**Preview:**

https://github.com/rightoneducation/righton-app/assets/79417944/31922372-dcd9-43a4-9115-c1e6396edab2

### CODE REVIEW

**Comment by amarax** [comment]
That looks good @drewjhart! 

Could we adjust the animation to be 4 stages instead:
1. The wiggle lasts 1.5s with a 0.5s pause after
2. There is a slight move up about half the height ease-in-out 0.3s
3. The slide down and fade is ease-in 1s
4. (Optional) the blue score grows and shrinks back 1s

**Comment by drewjhart** [comment]
> That looks good @drewjhart!
> 
> Could we adjust the animation to be 4 stages instead:
> 
> 1. The wiggle lasts 1.5s with a 0.5s pause after
> 2. There is a slight move up about half the height ease-in-out 0.3s
> 3. The slide down and fade is ease-in 1s
> 4. (Optional) the blue score grows and shrinks back 1s

Sweet, thanks! I'll make the above adjustments

**Comment by drewjhart** [comment]
Hey @amarax, I've updated the animation per your comments. Here's a preview:

https://github.com/rightoneducation/righton-app/assets/79417944/779f5a8d-9279-40e9-a022-4059174f6646

**Comment by drewjhart** [comment]
> @drewjhart could we add the easing for the translateY transforms for animation phases 2-3? Sorry to be nitpicky haha. If you don't have time we can just ship it as is!

hahaha all good. Could you explain further though? Currently for the green pill we have:

```
  animation: `
   newScoreUpWiggle 1500ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,
   newScoreUpBounce 300ms ease-in-out 1500ms, 
   newScoreUpFadeDown 1000ms ease-in-out 1800ms
  `,
  ```
  
  Is the effect not showing properly though?

**Pull request merged**
